# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./build

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'oracle'
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
    - name: Zip files
      if: false
      run: zip install.zip jar/FXCoreMP.jar *.cmd ../eclipse/ ../notepadpp
    - name: List files
      run: ls -la
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: install
        path: |
          build/jar/FXCoreMP.jar 
          bild/*.cmd 
          eclipse/ 
          notepadpp/ 
          test/SamplePgm.fxc
        if-no-files-found: error
