# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

# Trigger this workflow on any push to MAIN branch
on:
  push:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./build # Note this is used only for RUN steps, not USES

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone
      uses: actions/checkout@v4 # This will checkout (clone) the repo to this build machine
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'oracle'
        
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
      
    - name: Zip files
      if: false
      run: zip install.zip jar/FXCoreMP.jar *.cmd ../eclipse/ ../notepadpp
      
    - name: List files
      if: false
      run: ls -la

    - name: Copy install files
      run: |
        mkdir ../bin
        mkdir ../samples
        cp ../build/jar/FXCoreMP.jar ../bin
        cp ../build/*.cmd ../bin
        cp ../test/SamplePgm.fxc ../samples
        
    - name: Upload old
      uses: actions/upload-artifact@v4
      with:
        name: install # Artifact will be zip of PATH files as <name>.zip
        path: |
          bin/
          samples/
          notepadpp/
          eclipse/
        if-no-files-found: error
      
    - name: Upload old
      if: false
      uses: actions/upload-artifact@v4
      with:
        name: install # Artifact will be zip of PATH files as <name>.zip
        path: |
          build/jar/FXCoreMP.jar 
          build/*.cmd 
          eclipse/ 
          notepadpp/ 
          test/SamplePgm.fxc
        if-no-files-found: error
